security:
    encoders:
        Aris\MainBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity:
                class: Aris\MainBundle\Entity\User
                property: username

    firewalls:
        admin:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  login
                check_path:  login_check
            logout:
                path:   /logout
                target: /login

    access_control:
           - { path: ^/admin, roles: ROLE_ADMIN }